### ISSUE TITLE
Some issues with `blamer--get-background-color`

### ISSUE THREAD

**Issue by d1egoaz** [Artawower/blamer.el#13]
Hello, thanks for this great package.

I've been having some issues when blamer is trying to get the background/foreground colors.

I wonder if there is a way to disable the smart background and only use `blamer-face`?

- With `highlight-parentheses-mode` enabled:
```
Error running timer ‘blamer--render’: (error "Invalid face" :inherit bold :foreground "firebrick1")
```

- With `show-parens-mode` enabled and point in a parenthesis:
 
![image](https://user-images.githubusercontent.com/950087/140168723-45ed5493-cb7d-409f-92c6-876c3d41a1f6.png)

Point not in a parenthesis:
![image](https://user-images.githubusercontent.com/950087/140168654-5e91f80d-aeec-43fc-a2f6-fdb73b78a1d9.png)

If a set `blamer-face` with a specific background color (black), this is what I'm getting:
![image](https://user-images.githubusercontent.com/950087/140169005-999ae68f-150f-40a1-8e0c-977adc054703.png)

- A random error:
```
Error running timer ‘blamer--render’: (error "Invalid face" :background "#7d867d997da0")
```

**Comment by brownts** [comment]
I've noticed a similar issue with the wrong background color being extended to the overlay.  I recently switched from beacon to pulse (`pulse-momentary-highlight-one-line`), since the beacon animation didn't seem to play nice with the blamer overlay (i.e., would momentarily push the overlay text to the right in some instances where the animation went beyond the end of the text for that line).  For pulse, It appears that blamer.el is picking up on this transient background color for the pulse (for example when switching windows and the pulse is activated) and thus the overlay will end up keeping the background color even after the pulse background color over the normal text has been removed.

**Comment by Artawower** [comment]
Hi, thanks for the feedback 👍

Hmm...yes I understand the problem, now the background color is taken from under the cursor. It needs to be taken from the actual overlay position. However, it is not part of the text until the moment of insertion. I will think about how to improve this behavior.

**Comment by Artawower** [comment]
First of all, i added special variable for disabling smart background detection, you can disable it:
`(setq blamer-smart-background-p nil)`
I this case blamer will prefer own face everytime

Also i fixed some errors and tried to improve background detection by `blamer--get-background-color` function, i hope it will be better.

Tell me if you are still experiencing this problem

**Comment by d1egoaz** [comment]
I updated to latest blamer.el version, and it fixed all the issues for me with smart background enabled.

Thanks
