### ISSUE TITLE
Line breaks with a small viewport

### ISSUE THREAD

**Issue by ckruse** [Artawower/blamer.el#28]
Hey there,

blamer.el causes line breaks when used in a small viewport:

<img width="982" alt="Bildschirmfoto 2022-02-22 um 09 58 35" src="https://user-images.githubusercontent.com/175095/155097806-e00dc83e-0481-4d2f-9feb-6f906a2e9ba1.png">

This leads to very confusing jumps (line break appears, disappears, appears, …, depending on the length of the line). Is there a way to avoid these breaks?

Best regards,
 CK

**Comment by Artawower** [comment]
Hello, thanks for your report, I am aware of this problem [problem](https://github.com/Artawower/blamer.el/issues/15#issuecomment-966128987), right now there is no way to fix it with the current implementation. I will try to fix it in the next commit soon.
For now, you can disable `truncate-long-lines` or disable blamer mode and enable commit information by pressing the shortcut, for example:

```elisp
(use-package blamer
  :defer t
  :bind (("s-i" . blamer-show-commit-info)
             ("C-c i" . (lambda () (interactive) (blamer-show-commit-info 'visual)))) ;; C-c i will show commit info about current line

 :configs
  ;; other configs...
  ;; (global-blamer-mode 1) - blamer mode is disabled, and actions handled by you self
)
```
Honestly, this is expected behavior for me, because when user enable line break mode, it makes sense to move the current sentence about git blame information, but when several people think it should work differently... I think I'll add a variable to customize this behavior for better user experience..

**Comment by ckruse** [comment]
Thank you!

**Comment by Artawower** [comment]
Made in the latest release. Could you please check it?

**Comment by ckruse** [comment]
As far as I understand it there should be no line breaks when `blamer-force-truncate-long-line` is set to `t`, correct?

If yes: sorry :( lines breaks still happen.

<img width="973" alt="Bildschirmfoto 2022-02-25 um 07 05 21" src="https://user-images.githubusercontent.com/175095/155663300-b1b1ca38-df6c-4aeb-a64f-9af11b24b899.png">

**Comment by Artawower** [comment]
Oh, at first I thought it was a line translation problem, but in the last screenshot I see that it happened in a situation where line translation should not happen... I need to think about this problem.

Could you please let me know the name of the font? Right now the only idea I have is that different fonts have different character widths

**Comment by ckruse** [comment]
It is Source Code Pro-12

**Comment by Artawower** [comment]
I think it was not a font issue. Could you try the latest commit?

**Comment by ckruse** [comment]
It works now 🥳 thank you very much!
