### ISSUE TITLE
`(wrong-type-argument stringp nil)` when no commit associated with line

### ISSUE THREAD

**Issue by gekoke** [Artawower/blamer.el#59]
I believe this might be a regression since I haven't experienced this before.

The source of the error is the `commit-infos` function.

I don't know how to provide a better backtrace, since I'm running the package byte-compiled.

Reproduction: place cursor on any line with no associated commit. E.g., create a couple empty lines in a file tracked by Git.

Version info:
```
;; Package-Version: 20240128.1314
;; Package-Commit: 412fea9e0564929310918096bae95636ba885a7c
;; Package-Requires: ((emacs "27.1") (posframe "1.1.7") (async "1.9.7"))
;; Version: 0.8.1
```

**Comment by Artawower** [comment]
Yes, it's regression, I recently moved most of the logic to asynchronous execution. It's very difficult to debug. 

Should have been fixed in the last commit. 

Btw, I added a flag `blamer-enable-async-execution-p`, if you encounter this error, you can set this variable to nil for better backtracing
